<h2>Documentation</h2>
	
<ul>
	<li><a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=/">Index</a></li>
	
	<?php foreach ($RAML->getChildPaths('/') as $endpoint => $resource) { ?>
	<li><a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=<?php echo $endpoint; ?>"><?php echo $endpoint; ?></a></li>
	<?php } ?>
</ul>

<p>&nbsp;</p>

<h2>Server Status</h2>
<?php
$status = $RAML->pingStatus();
if ($status == 'online'): ?>
	<span class="online">ONLINE</span>
<?php else: ?>
	<span class="offline">CURRENTLY DOWN!</span>
<?php endif; ?>
<br />
<small>Updated every 5 minutes</small>